uwdata/mosaic

- docs/.vitepress/config.js
- docs/examples/sorted-bars.md
- docs/public/specs/esm/sorted-bars.js
- docs/public/specs/json/sorted-bars.json
- docs/public/specs/yaml/sorted-bars.yaml
- packages/vgplot/src/marks/Mark.js
- packages/vgplot/src/marks/util/is-constant-option.js
- Add mark sort and filter option support.
- Add sorted bars example to docs.
Close #122
> Add mark sort and filter option support.

- package-lock.json
- package.json
- packages/vgplot/package.json
> Bump dependencies.

- dev/notebooks/motherduck.ipynb
This way everyone with access can run the example
> docs: use motherduck gaia dataset from a share

- packages/core/src/util/js-type.js
fixes https://github.com/uwdata/mosaic/issues/233
> add type 'TIMESTAMP WITH TIME ZONE'

- packages/core/src/util/js-type.js
> feat: add type 'TIMESTAMP_NS' field type

- packages/vgplot/src/spec/parse-spec.js
- packages/vgplot/src/spec/to-module.js
> feat: Add ability to specify arbitrary aggregations in json

- package-lock.json
- packages/widget/package.json
- packages/widget/pyproject.toml
Just a minor bump in preparation for anywidget updates coming with https://github.com/manzt/anywidget/pull/395
> chore: update anywidget to 0.8.1

- .github/workflows/test.yml
- package-lock.json
- packages/widget/package.json
- packages/widget/pyproject.toml
- packages/widget/src/index.js
Use new any widget lifecycle methods: https://github.com/manzt/anywidget/releases/tag/anywidget%400.9.0.
> chore: update anywidget and ruff

- docs/api/vgplot/marks.md
Found this link somewhere else in the docs.
> docs: Add link for "M4 Optimization"

- packages/duckdb-server/pkg/server.py
- packages/duckdb-server/pyproject.toml
- packages/widget/pyproject.toml
- Update server and widget to use DuckDB 9.2.
- Fix server to pass exceptions to logger.
> Update server and widget

- packages/duckdb-server/pkg/server.py
- packages/widget/mosaic_widget/__init__.py
See https://docs.astral.sh/ruff/rules/verbose-log-message/
> style: correct call to logger.exception

- packages/inputs/src/Menu.js
> fix: allow menu selector to filter to non-truthy values like column=0

- dev/notebooks/specs.ipynb
- dev/notebooks/weather.ipynb
- packages/widget/mosaic_widget/__init__.py
> fix: support windows and update paths in example notebooks

- packages/core/src/DataCubeIndexer.js
- packages/core/src/FilterGroup.js
- packages/core/test/data-cube-indexer-test.js
- packages/core/test/util/node-connector.js
- packages/core/test/util/test-client.js
- Add support for ARG_MIN, ARG_MAX aggregates.
- Add support for PRODUCT, BIT_AND, BIT_OR, BIT_XOR, BOOL_AND, BOOL_OR aggregates.
> Add more aggregates to DataCubeIndexer.

- packages/sql/src/to-sql.js
- packages/sql/test/literal-test.js
This fixes issues with text columns that contain `'`.
> fix: escape strings with '

- packages/core/src/connectors/rest.js
- packages/core/src/connectors/socket.js
- packages/core/src/connectors/wasm.js
also make query type type more specific
> docs: add comments for query methods of all connectors

- packages/core/src/Coordinator.js
- packages/core/src/MosaicClient.js
- packages/plot/src/marks/RegressionMark.js
- Fix empty data handling in regression mark.
- Fix query error handling in coordinator and clients.
> Fix empty data in regression mark, query error handling.

- packages/core/src/DataCubeIndexer.js
- packages/core/src/util/index-columns.js
- packages/plot/src/marks/HexbinMark.js
- packages/plot/src/plot.js
- Add support for plot `aspectRatio` property when auto-calculating heights at the Mosaic level.
- Add groupby and flexible column reference support to `hexbin` mark queries.
- Update data cube index column analysis, use more flexible groupby handling.
> Miscellaneous updates.

- packages/plot/src/legend.js
- packages/plot/src/plot-attributes.js
- packages/spec/src/spec/PlotAttribute.ts
- packages/vgplot/src/api.js
- packages/vgplot/src/plot/attributes.js
- Add `rLabel` plot attribute.
- Update legend to look up plot label attributes.
> Improve scale label support.

- data/penguins.json
- packages/duckdb/src/load/json.js
- packages/duckdb/test/duckdb-test.js
fixes https://github.com/uwdata/mosaic/issues/455
> fix: Add test for loadJSON and remove broken usage of `json_format`

- .vscode/launch.json
I found this useful to add breakpoints in vscode. Maybe you have another workflow.
> chore: add launch file to run mocha tests for current file

- packages/sql/package.json
- packages/sql/tsconfig.json
> feat: add type declarations to sql

- packages/duckdb-server-rust/Cargo.lock
- packages/duckdb-server-rust/src/db.rs
> chore: change execute_batch -> execute, update deps

- .gitignore
- dev/index.html
- dev/parse.html
- packages/plot/src/interactors/Nearest.js
- packages/plot/src/interactors/Toggle.js
- packages/plot/src/plot-renderer.js
- Update facet handling to follow changes in Observable Plot.
- Add local test spec loading in dev runner.
> Update facet handling.

- packages/core/README.md
- packages/duckdb/README.md
- packages/inputs/README.md
- packages/plot/README.md
- packages/spec/README.md
- packages/sql/README.md
- packages/vgplot/README.md
shows the latest versions and a link to npm
> docs: add badges to readmes

- packages/plot/src/marks/HexbinMark.js
- Fix hexbin query y-coordinate calculation.
> Fix hexbin query.

- docs/public/specs/esm/line-multi-series.js
- docs/public/specs/esm/region-tests.js
- docs/public/specs/json/line-multi-series.json
- docs/public/specs/json/region-tests.json
- docs/public/specs/yaml/line-multi-series.yaml
- docs/public/specs/yaml/region-tests.yaml
- specs/esm/line-multi-series.js
- specs/esm/region-tests.js
- specs/json/line-multi-series.json
- specs/json/region-tests.json
- specs/ts/line-multi-series.ts
- specs/ts/region-tests.ts
- specs/yaml/line-multi-series.yaml
- specs/yaml/region-tests.yaml
- Update examples for better dark mode viewing. (Fixes #600)
> Update examples for better dark mode viewing.

- dev/index.html
- docs/.vitepress/config.js
- docs/examples/athlete-birth-waffle.md
- docs/public/specs/esm/athlete-birth-waffle.js
- docs/public/specs/json/athlete-birth-waffle.json
- docs/public/specs/yaml/athlete-birth-waffle.yaml
- packages/spec/src/spec/PlotMark.ts
- packages/spec/src/spec/marks/Waffle.ts
- packages/vgplot/src/api.js
- packages/vgplot/src/plot/marks.js
- specs/esm/athlete-birth-waffle.js
- specs/json/athlete-birth-waffle.json
- specs/ts/athlete-birth-waffle.ts
- specs/yaml/athlete-birth-waffle.yaml
- Add waffle mark support and typings.
- Add `athletes-birth-waffle` example.
Close #597.
> Add waffle mark.

- packages/core/src/Coordinator.js
- packages/core/src/MosaicClient.js
- packages/core/src/types.ts
- packages/core/src/util/field-info.js
- packages/core/src/util/js-type.js
- packages/inputs/src/Table.js
- packages/plot/src/marks/Mark.js
- Extract and refine `FieldInfo` types to .ts file.
> Extract and refine FieldInfo types to .ts file.

- data/us-president-favorability.csv
Fixed bug with Theodore Roosevelt's image URL.
> fix: updated outdated image link on examples page (presidential opinion)

- docs/.vitepress/config.js
- docs/api/core/client.md
- docs/core/index.md
- docs/web-clients/index.md
- docs/web-frameworks/index.md
- package-lock.json
- packages/core/src/Coordinator.js
- packages/core/src/MosaicClient.js
- packages/core/src/index.js
- packages/core/src/make-client.js
- packages/core/test/client.test.js
- packages/core/test/make-client.test.js
- packages/core/test/preaggregator.test.js
- packages/svelte-example/.gitignore
- packages/svelte-example/README.md
- packages/svelte-example/index.html
- packages/svelte-example/jsconfig.json
- packages/svelte-example/package.json
- packages/svelte-example/public/seattle-weather.csv
- packages/svelte-example/src/App.svelte
- packages/svelte-example/src/app.css
- packages/svelte-example/src/lib/Count.svelte
- packages/svelte-example/src/lib/Histogram.svelte
- packages/svelte-example/src/lib/MainView.svelte
- packages/svelte-example/src/lib/Plots.svelte
- packages/svelte-example/src/main.js
- packages/svelte-example/src/react/Count.jsx
- packages/svelte-example/src/vite-env.d.ts
- packages/svelte-example/svelte.config.js
- packages/svelte-example/vite.config.js
A contribution from Apple (via @donghaoren and @domoritz).
Add a `makeClient` API to make it easier to build Mosaic views with modern frameworks such as React or Svelte.
Fixes #394 and https://github.com/uwdata/mosaic/discussions/482. 
Here is how one might use it in Svelte 5 syntax. This examples shows a simple sum of a given field.
```svelte
<script>
let { table, field, filter, coordinator } = $props();
let currentSum = $state(null);
$effect(() => {
// Create the Mosaic client, and re-create it whenever any of the table, field,
// filter, coordinator props change. Note that for the filter, a "change" here means
// the filter is set to a new instance of Selection, rather than a change of the
// current selection's value.
let client = makeClient({
coordinator: coordinator,
selection: …
```
> feat: makeClient API

- packages/core/vitest.config.ts
- packages/duckdb/vitest.config.ts
- packages/inputs/vitest.config.ts
- packages/plot/vitest.config.ts
- packages/spec/vitest.config.ts
- packages/sql/vitest.config.ts
- packages/vgplot/vitest.config.ts
- vitest.config.ts
- vitest.workspace.ts
- Update test config so that we can run tests from within packages again.
> chore: add vitest config files to individual packages

- packages/core/src/preagg/PreAggregator.js
- packages/core/test/preaggregator.test.js
- Fix preaggregator by ensuring group by columns are correctly pushed down to subqueries that perform aggregation.
> Push preagg group by columns to aggregate subqueries.

- packages/core/src/Selection.js
- Add Selection reset method to clear a selection of all clauses.
> Add Selection reset method.

- eslint.config.js
- package-lock.json
- package.json
- packages/core/src/QueryConsolidator.js
- packages/core/src/Selection.js
- packages/core/src/SelectionClause.js
- packages/core/src/preagg/PreAggregator.js
- packages/core/src/preagg/preagg-columns.js
- packages/core/src/preagg/sufficient-statistics.js
- packages/core/src/util/field-info.js
- packages/inputs/package.json
- packages/inputs/src/Menu.js
- packages/inputs/src/Search.js
- packages/inputs/src/Slider.js
- packages/inputs/src/Table.js
- packages/inputs/src/util/format.js
- packages/plot/src/marks/Grid2DMark.js
- packages/plot/src/marks/Mark.js
- packages/spec/src/ast-to-dom.js
- packages/spec/src/ast-to-esm.js
- packages/spec/src/config/extensions.js
- packages/sql/src/ast/select.js
- packages/sql/src/ast/window.js
- packages/sql/src/ast/with.js
- packages/sql/src/functions/column.js
- packages/sql/src/functions/cte.js
- packages/sql/src/visit/rewrite.js
- packages/sql/src/visit/visitors.js
- Update lint rules, fix violations.
> Update lint rules, fix violations.

- packages/sql/src/visit/rewrite.js
- Fix SQL `rewrite` helper so that it does not mutate input.
> Fix SQL rewrite, do not mutate input.

- packages/mosaic/core/src/connectors/wasm.ts
This exposes the native DuckDBConfig object on the connector, which right now only enables two things:
- path (OPFS support)
- accessMode
I couldn't see a good place to add a test for this, it doesn't appear like there is WASM specific testing. Are there any concerns with this approach?
> feat: enable DuckDBConfig for OPFS support

- package-lock.json
- packages/mosaic/core/test/client.test.ts
- packages/mosaic/core/test/make-client.test.ts
- packages/mosaic/core/test/preaggregator.test.ts
- packages/mosaic/core/test/util/node-connector.ts
- packages/server/duckdb/src/DuckDB.js
- packages/vgplot/vgplot/test/render.test.js
This should fix these occasional issues (which were bothering me enough to fix it).
> ci: fix occasional test faliures

- packages/server/duckdb-server-go/.golangci.yaml
- packages/server/duckdb-server-go/README.md
- packages/server/duckdb-server-go/go.mod
- packages/server/duckdb-server-go/internal/query/query.go
- packages/server/duckdb-server-go/internal/query/query_test.go
- packages/server/duckdb-server-go/internal/query/validator.go
- packages/server/duckdb-server-go/internal/query/validator_test.go
- packages/server/duckdb-server-go/internal/server/server.go
- packages/server/duckdb-server-go/main.go
> duckdb-go-server: production style enhancements

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Switch to new LTS: https://endoflife.date/nodejs.
> ci: node 22
