uwdata/mosaic

- packages/vgplot/src/transforms/bin.js
If I understood `binField` and `bins` functions correctly, `min` provided by `bins` should be used for the output of `binField` since `nice=true` changes the `min`.
This PR replaces `min` to `b.min`
> fix: change binField to use min provided by bins

- dev/index.html
- dev/yaml/highlight-cube.yaml
- packages/core/src/DataCubeIndexer.js
- Include `orderby` criteria in generated data cube index queries.
- Add dev `highlight-cube` example to test consistent ordering of cube query results. (thanks @spren9er!)
Prior to this PR, any orderby criteria were applied upon data cube creation, but not upon subsequent queries to the resulting data cube index table. This PR reverses the situation: orderby criteria are stripped (ignored) for cube creation, but subsequently applied to all cube index table queries to ensure correct and consistent ordering of result rows.
This change fixes the observed ordering inconsistencies between normal and data cube index query results, fixing known highlight interactor bugs over ordered data. (It does not fix the underlying issue that highlight bit vector queries may have different orderings from …
> Push orderby criteria to data cube index queries.

- packages/vgplot/src/marks/Mark.js
- packages/vgplot/src/marks/RegressionMark.js
- packages/vgplot/src/marks/util/grid.js
- packages/vgplot/src/marks/util/is-arrow-table.js
- packages/vgplot/src/marks/util/to-data-array.js
- Map Arrow Timestamp types to JS `Date` objects, rather than numbers.
- Map Arrow Int64 types to JS `Number` instances, rather than `BigInt`. (FWIW, Plot already does this internally.)
These changes apply to unpacking of Arrow tables within vgplot only. We unpack an Arrow table into an array-of-objects format. This was already happening implicitly (using possibly slower Proxy objects); we now do it explicitly with control over type conversions. In the future, if [Plot adds support for columnar data](https://github.com/observablehq/plot/issues/191) we could modify our approach to take advantage of that and reduce data copy costs.
Mosaic client implementations still receive a standard, unaltered Arrow table. This PR targets vgplot mark internals.
Possible future work:
- coerce other types, …
> Coerce selected Arrow types in vgplot.

- dev/yaml/highlight-toggle.yaml
- docs/api/vgplot/interactors.md
- packages/vgplot/src/directives/interactors.js
- packages/vgplot/src/interactors/Toggle.js
Currently, a _toggle_ interactor — interacting with one mark — will filter out data of other marks in same plot, when used with cross-filter selection.
- Add `peers` attribute to _toggle_ interactor (analog to _interval_ interactors)
- Update `highlight-toggle.yaml` example, which uses now `peers` attribute under the hood to show **all** text labels when toggling (before, it showed only labels for selected bars)
- Update documentation of _toggle_ interactor
> Add peers attribute to toggle interactor

- packages/sql/src/operators.js
- packages/sql/test/operator-test.js
- Add parens around generated logical (AND, OR) operators when given two or more clause arguments.
This PR should serve as a fix / workaround for #191. Closes #191.
> Logical operators should include parens.

- packages/duckdb/src/data-server.js
- packages/duckdb/src/index.js
fixes https://github.com/uwdata/mosaic/issues/236
> feat: export Cache, queryHandler and socketResponse

- packages/duckdb/src/DuckDB.js
I need to install unsigned extensions, so when I instantiate my duckdb class I need to pass a [configuration object](https://duckdb.org/docs/sql/configuration#configuration-reference) like so:
```js
new DuckDB.Database(":memory:", {
allow_unsigned_extensions: "true",
})
```
I also need to be able to install the arrow extension from a `custom_extension_repository` so ideally I'd be able to override the `CONFIG` as well
> add configuration options for DuckDB class

- packages/core/src/DataCubeIndexer.js
Aggregate expressions include an `aggregate` key indicating they perform aggregation. For normal aggregation functions, this key is a string value indicating the aggregate operation. However, custom aggregate expressions are also possible, indicated by a boolean `true` value for the `aggregate` key.
The data cube indexer refers to the `aggregate` key to try to identify indexing opportunities. This PR fixes a bug where this process breaks due to assuming a string value. The current fix is to fall through to the default action (which does not perform any indexing) when non-string values are observed.
Fix #263.
> Fix index column identification with non-string aggregate key.

- dev/yaml/highlight-cube.yaml
- dev/yaml/weather.yaml
- docs/public/specs/esm/weather.js
- docs/public/specs/json/weather.json
- docs/public/specs/yaml/weather.yaml
- packages/vgplot/src/interactors/Highlight.js
- packages/vgplot/src/marks/HexbinMark.js
- packages/vgplot/src/marks/Mark.js
- packages/vgplot/src/plot-attributes.js
- packages/vgplot/src/plot-renderer.js
This PR fixes a [bug](https://github.com/uwdata/mosaic/issues/248) in which the `highlight` interactor may highlight the wrong items if the data ordering of the visualized data is inconsistent with highlight query results. A workaround was to add sort criteria to ensure consistent ordering. This PR updates the `highlight` interactor to automatically add appropriate orderby criteria to a highlighted mark when needed.
**Breaking change:** This PR also addresses a conflict where the mark-level `order` option (which specified query orderby criteria) can be confused with Observable Plot's `order` option, which parameterizes internal stacking transforms. This update now uses a non-conflicting `orderby` option, leaving `order` as a Plot-specific option. **Any existing specifications which use …
> Use orderby, not order. Allow highlight to automatically set orderby.

- dev/yaml/moving-average.yaml
- docs/public/specs/json/moving-average.json
- docs/public/specs/yaml/moving-average.yaml
- packages/vgplot/src/spec/parse-spec.js
- packages/vgplot/src/spec/to-module.js
Previously, the specification for a window transform within an encoding channel used `order` for the window ORDER BY criteria and `partition` for the PARTITION BY criteria. This PR renames those keys to `orderby` and `partitionby`, which more closely matches SQL and improves consistency with Mosaic's SQL helpers and also mark-level `orderby` criteria.
This is a **breaking change**. Any specs that previously used window transforms with `order` or `partition` need to be updated to use `orderby` and `partitionby` instead.
> Rename YAML/JSON spec window function orderby, partitionby

- package-lock.json
- packages/widget/package.json
- packages/widget/src/index.js
> fix: use uuid package instead of crypto for remote http jupyters

- docs/api/core/connectors.md
rest uses `http` sockets is `ws`
> docs: fix default protocol in core/connectors

- packages/plot/src/marks/ContourMark.js
- packages/plot/src/marks/Mark.js
- packages/plot/src/marks/RasterMark.js
- packages/plot/src/marks/RegressionMark.js
- Pass `tip` option to `regression` mark error band only, providing a single informative tooltip.
- Fix `raster` mark transient scale domain updates to get appropriate domain definitions.
- Fix `contour` mark fill/stroke/opacity encoding channel generation for density thresholds.
> Fixes and refinements

- dev/index.html
- docs/public/specs/esm/aeromagnetic-survey.js
- docs/public/specs/esm/legends.js
- packages/spec/src/ast-to-esm.js
- packages/spec/src/ast/HSpaceNode.js
- packages/spec/src/ast/InputNode.js
- packages/spec/src/ast/PlotAttributeNode.js
- packages/spec/src/ast/PlotInteractorNode.js
- packages/spec/src/ast/PlotLegendNode.js
- packages/spec/src/ast/PlotMarkNode.js
- packages/spec/src/ast/TransformNode.js
- packages/spec/src/ast/VSpaceNode.js
- packages/vgplot/src/plot/named-plots.js
- specs/esm/aeromagnetic-survey.js
- specs/esm/legends.js
- Add `preamble` option to `astToESM`.
- Fix `hspace`/`vspace` codegen to properly stringify values.
- Fix `namedPlots.clear()` to also clear queued requests.
- Fix proper context use in AST node `instantiate()` calls.
- Update dev example runner.
> Address AST context and instantiation issues.

- packages/plot/src/interactors/Interval1D.js
- packages/plot/src/interactors/Interval2D.js
- packages/plot/src/interactors/Nearest.js
- packages/plot/src/interactors/PanZoom.js
- packages/plot/src/interactors/Toggle.js
- Fix interactors to avoid firing activate events if the mouse is being dragged.
Supercedes #339.
> Only activate selections when the mouse button is up.

- .github/workflows/deploy.yml
- packages/plot/src/marks/Grid2DMark.js
- packages/plot/src/marks/Mark.js
- packages/plot/src/plot.js
I was hoping it would help detect things like #345 but we would need even stronger types.
> docs: add types for setPlot and plot attributes

- packages/duckdb-server/pyproject.toml
- packages/widget/pyproject.toml
uv is way faster than pip for installing dependencies. See https://github.com/pypa/hatch/issues/1268
Needs a new release of hatch to actually work but will not break either.
> chore: use uv for installing python deps

- packages/core/src/DataCubeIndexer.js
- packages/core/src/FilterGroup.js
- packages/core/src/Selection.js
Previously, data cube indexes were constructed only when _all_ filtered clients in a Selection were indexable. This PR relaxes this restriction: we now build data cube index tables for indexable clients while using standard, unoptimized selection update queries for any others.
> Support partial data cube indexes.

- packages/core/src/Selection.js
- packages/inputs/src/Menu.js
- Add Selection `valueFor` to look up source-specific values.
- Fix Menu value initialization and updates. (#401)
> Update inputs and selection.

- packages/core/src/DataCubeIndexer.js
- packages/core/src/SelectionClause.js
- packages/core/src/index.js
- packages/inputs/src/Menu.js
- packages/inputs/src/Search.js
- packages/inputs/src/Slider.js
- packages/plot/src/interactors/Interval1D.js
- packages/plot/src/interactors/Interval2D.js
- packages/plot/src/interactors/Nearest.js
- packages/plot/src/interactors/PanZoom.js
- packages/plot/src/interactors/Toggle.js
- packages/sql/src/index.js
- **Breaking**: Rename selection clause `schema` property to `meta`.
- Add selection clause generation methods (`point`, `interval`, etc).
- Add selection clause typings.
- Use selection clause methods in inputs and interactors.
- Export `SQLExpression` from `mosaic-sql` package.
> Add selection clause methods and types.

- packages/inputs/src/Menu.js
- packages/inputs/src/Search.js
- packages/inputs/src/Slider.js
- packages/inputs/src/Table.js
- packages/spec/src/spec/Input.ts
- Add `field` option to inputs (menu, slider, search) to control the column referenced in selection clause predicates.
- Update input documentation and types.
Addresses #406.
> Add selection field option to inputs.

- packages/core/src/Selection.js
- packages/core/src/index.js
- packages/core/src/util/to-data-columns.js
- packages/inputs/src/Table.js
- packages/plot/src/marks/Density1DMark.js
- packages/plot/src/marks/ErrorBarMark.js
- packages/plot/src/marks/Grid2DMark.js
- packages/plot/src/marks/Mark.js
- packages/plot/src/marks/RegressionMark.js
- packages/spec/src/ast/ParamNode.js
- packages/spec/src/ast/SelectionNode.js
- packages/spec/src/spec/Input.ts
- packages/spec/src/spec/Param.ts
- Add `empty` flag to selections. If true, selections with no clauses will not select any values. If false (the default), selections with no clauses select all data values.
- Add `as` selection option to `Table` input, for clauses corresponding to selected table row values.
- Move the `toDataColumns` utility from `mosaic-plot` to `mosaic-core`. This method maps Apache Arrow data to a set of native JS values.
TODO in future PRs
> Add empty selection and Table input support.

- packages/inputs/src/Table.js
- Fix `table` offset reset upon external updates.
Fixes #363.
> Reset table offset upon external update.

- packages/plot/src/transforms/bin-step.js
- packages/plot/src/transforms/bin.js
- packages/plot/src/transforms/time-interval.js
- packages/spec/src/ast/TransformNode.js
- packages/spec/src/spec/Transform.ts
- packages/sql/src/datetime.js
- packages/sql/src/index.js
- **Breaking**: Update declarative spec for `bin` transform to support top-level option properties, remove options object as second argument.
- Add date interval support to `bin` transform. A new `interval` option specifies a desired date/time unit (`hour`, `day`, `month`, etc) or forces standard numerical binning (`number`). If not specified, a reasonable date/time interval and step size will be determined automatically for temporal data.
- Add `dateBin` SQL helper method.
Close #427.
> Add date/time binning support.

- packages/core/src/SelectionClause.js
- packages/core/src/index.js
- packages/core/src/util/AsyncDispatch.js
- packages/core/test/client-test.js
- packages/inputs/src/Menu.js
- packages/inputs/src/Search.js
- packages/inputs/src/Slider.js
- packages/inputs/src/Table.js
- packages/plot/src/interactors/Interval1D.js
- packages/plot/src/interactors/Interval2D.js
- packages/plot/src/interactors/Nearest.js
- packages/plot/src/interactors/PanZoom.js
- packages/plot/src/interactors/Toggle.js
- Refactor clause generators for better clarity (`clauseInterval` instead of just `interval`).
- Add `pending()` method to `AsyncDispatch` to track param/selection event processing.
- Add test cases for client and selection lifecycle methods. (h/t @matys1)
> Refactor clause generator methods.

- packages/duckdb-server/pyproject.toml
- packages/widget/pyproject.toml
As I took a more thorough look at this project, inspecting how `hatch` is being used in a monorepo setting, I noticed that the creation of the Python virtual environments take longer than I would have expected, given that `uv` is supposed to be used.
Running `hatch env create` with `export HATCH_VERBOSE=1` confirmed that plain `pip` was used instead of `uv` for dependency installation.
Based on the latest docs (https://hatch.pypa.io/dev/how-to/environment/select-installer/#enabling-uv), `uv` needs to be enabled via `installer = "uv"` instead of `uv = true`. This PR adds the necessary changes.
> chore: enable `uv` via `installer` key

- packages/core/src/DataCubeIndexer.js
- packages/core/src/QueryManager.js
- packages/core/src/util/throttle.js
- packages/core/test/throttle-test.js
- Make throttle utility resilient to callback rejections
- Reject canceled queries rather than leaving them pending
- Index creation queries are no longer canceled when clearing the data cube indexes since the indexes may already be used in other queued requests
Fixes #458
> Fix missing index errors and updates that stop emitting

- packages/widget/pyproject.toml
this removes unnecessary files from the build
learned from https://github.com/manzt/quak/blob/main/pyproject.toml by @manzt
> chore: use only-packages in jupyter widget

- packages/duckdb-server-rust/Cargo.lock
- packages/duckdb-server-rust/Cargo.toml
- packages/duckdb-server-rust/src/db.rs
Fixes compilation of https://github.com/uwdata/mosaic/pull/462 by using an mpsc channel and tokio_streams.
The reason this is more complicated that what you were trying @domoritz , is that the `Arrow` type provided by the duckdb crate is not [Send](https://doc.rust-lang.org/nomicon/send-and-sync.html).  This means that it (and objects that depend on it) cannot be transferred across threads.  This is why it doesn't work to build a stream using the `stream!` macro and return it from inside the `conn.interact` closure.
Using mpsc channels like I am here is a common workaround for dealing with non-send objects. Here the Arrow object stays in the thread that constructed it, and pushes the record batches through the channel back to the main thread. This channel is wrapped into a stream using …
> Stream Arrow RecordBatches using mpsc channel and tokio_streams

- packages/core/src/QueryConsolidator.js
- packages/core/test/query-consolidator-test.js
In the `QueryConsolidator`, make sure `SELECT x FROM table` is not consolidated with `SELECT count() FROM table` since the aggregation in the latter query implies an implicit grouping which the former doesn't.
Implemented the fix by adding a GROUP BY * to the query's consolidation key where aggregates are present in the select.
Fixes #478
> fix: Don't consolidate aggregated and non-aggregated queries without a groupby

- packages/core/src/Coordinator.js
- packages/core/src/MosaicClient.js
- packages/core/src/util/index-columns.js
- packages/plot/src/plot.js
- Add client `initialize` method. This method supports dynamic client re-initialization, issuing new field info and client query requests.
- Update `Plot` to re-initialize mark clients upon dynamic field updates.
- Fix data cube indexer to generate correct averages in variance and covariance calculations. (#487)
Together, these changes allow vgplot to properly support dynamic fields, where the underlying database column for an encoding channel may change due to interactive updates.
Close #487.
> Add client initialize, fix data cube avg generator.

- packages/core/src/index.js
- packages/widget/package.json
- packages/widget/src/index.js
- Add `decodeIPC` for parsing Arrow data to `mosaic-core` exports.
- Update Jupyter widget to reflect latest updates and use `decodeIPC`.
Fix #499.
> Export shared IPC decoder, revise widget.

- packages/plot/src/interactors/Nearest.js
- Fix `nearest` interactor to use a `Param`-compatible clause for single-field selections.
Fix #502
> Use param-compatible clause for single-field nearest selection.

- packages/widget/mosaic_widget/__init__.py
The Mosaic widget not only supports Pandas data frames but any Arrow object (including other dataframes like polars).
re: https://github.com/manzt/quak/issues/54#issuecomment-2353416672
ref: https://duckdb.org/docs/api/python/data_ingestion#directly-accessing-dataframes-and-arrow-objects
> docs(widget): Clarify multi-dataframe/Arrow support for DuckDB

- packages/core/src/connectors/rest.js
- packages/core/src/connectors/socket.js
- packages/core/src/connectors/wasm.js
Not needed when the request is a bundle request but we do need other parameters then.
CC https://github.com/alexkreidler
> fix: correct connector types

- packages/duckdb/src/data-server.js
As discussed in https://github.com/uwdata/mosaic/issues/553, this returns the server so that the user can subsequently do things with it such as close it. 
I didn't see an existing test for booting up the server where it would make sense to add this scenario but if I missed something, let me know.
> feat: return dataServer on creation (#553)

- packages/duckdb-server-rust/Cargo.lock
- packages/duckdb-server-rust/Cargo.toml
Duckdb switched to arrow 53.1 so now cargo build fails with the following:
```
Compiling duckdb-server v0.1.1 (/mosaic/packages/duckdb-server-rust)
error[E0308]: mismatched types
--> src/db.rs:44:26
|
44  |             writer.write(&batch)?;
|                    ----- ^^^^^^ expected `arrow::array::RecordBatch`, found `duckdb::arrow::array::RecordBatch`
|                    |
|                    arguments to this method are incorrect
|
= note: `duckdb::arrow::array::RecordBatch` and `arrow::array::RecordBatch` have similar names, but are actually distinct types
note: `duckdb::arrow::array::RecordBatch` is defined in crate `arrow_array`
--> /.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-53.1.0/src/record_batch.rs:72:1
|
72  | pub struct RecordBatch {
| …
```
> fix: bump arrow to 53.1 to match duckdb and prevent build errors

- docs/public/specs/esm/line-multi-series.js
- docs/public/specs/json/line-multi-series.json
- docs/public/specs/yaml/line-multi-series.yaml
- specs/esm/line-multi-series.js
- specs/json/line-multi-series.json
- specs/ts/line-multi-series.ts
- specs/yaml/line-multi-series.yaml
- Fix `line-multi-series` example to use `currentColor` for text and point annotations upon hover.
> Use currentColor for multi-series label.

- packages/core/src/index.js
Currently, the generated type declaration file (`index.d.ts`) for `mosaic-core` does not include the types defined in `selection-types.ts`
This PR makes to include the types defined in `selection-types.ts` in the generated `index.d.ts` for `mosaic-core`
`index.d.ts` before this change
```typescript
export { MosaicClient } from "./MosaicClient.js";
export { Priority } from "./QueryManager.js";
export { restConnector } from "./connectors/rest.js";
export { socketConnector } from "./connectors/socket.js";
export { wasmConnector } from "./connectors/wasm.js";
export { decodeIPC } from "./util/decode-ipc.js";
export { distinct } from "./util/distinct.js";
export { isArrowTable } from "./util/is-arrow-table.js";
export { synchronizer } from "./util/synchronizer.js";
export { throttle } from …
```
> feat: export selection types

- packages/core/src/QueryConsolidator.js
- packages/core/src/QueryManager.js
If you want to get the queries that are being run, you can disable caching and consolidation and create a wrapper connector like
```js
export function loggerConnector(connector) {
const logs = [];
return {
snapshot() {
return logs;
},
async query(query) {
const result = await connector.query(query);
logs.push({query, result});
return result;
}
}
}
```
> feat: remove unused recorder code

- packages/inputs/src/Table.js
- packages/plot/src/marks/DenseLineMark.js
- packages/plot/src/marks/Density1DMark.js
- packages/plot/src/marks/ErrorBarMark.js
- packages/plot/src/marks/Grid2DMark.js
- packages/plot/src/marks/HexbinMark.js
- packages/plot/src/marks/Mark.js
- packages/plot/src/marks/RasterTileMark.js
- packages/spec/src/ast/PlotFromNode.js
- packages/spec/src/spec/Input.ts
- packages/spec/src/spec/PlotFrom.ts
- Add Param-value support for `from` table names in vgplot marks and table views. This change permits dynamic swapping of backing data tables at runtime, including among differently sized samples.
> Support param-valued data tables.

- packages/core/src/SelectionClause.js
- packages/inputs/src/Menu.js
- packages/inputs/src/Search.js
- packages/inputs/src/Slider.js
- Add selection activation for inputs. Inputs trigger selection activation upon keyboard focus or pointer enter (when a drag is not in progress).
> Add selection activation for inputs.

- packages/plot/src/marks/Mark.js
- packages/sql/src/ast/column-param.js
- packages/sql/src/index.js
- packages/sql/src/visit/visitors.js
- Fix dynamic column handling. Ensure column extraction includes column params. Within vgplot marks, do not use column name as alias if it is a dynamic param.
Close #610.
> Fix dynamic column handling.

- packages/plot/src/marks/Density1DMark.js
- packages/spec/src/spec/marks/Density.ts
- Add density 1D `normalize` option. If set to `true, scales density estimates by the total (weighted) point mass.
See also #606.
> Add density 1D normalize option.

- dev/index.html
- docs/.vitepress/config.js
- docs/examples/density-groups.md
- docs/public/specs/esm/density-groups.js
- docs/public/specs/json/density-groups.json
- docs/public/specs/yaml/density-groups.yaml
- packages/inputs/src/Menu.js
- packages/plot/src/marks/Density1DMark.js
- packages/plot/src/marks/util/grid.js
- packages/plot/src/marks/util/is-constant-option.js
- packages/spec/src/spec/Param.ts
- packages/spec/src/spec/marks/Density.ts
- packages/sql/src/transforms/bin-linear-1d.js
- packages/sql/src/transforms/bin-linear-2d.js
- specs/esm/density-groups.js
- specs/json/density-groups.json
- specs/ts/density-groups.ts
- specs/yaml/density-groups.yaml
- Add groupby and stack support to `densityX` and `densityY` marks.
- Add `groupby` argument to `binLinear1D` SQL function.
- Add `density-groups` example.
- Expand param typing to accept `null` value.
- Fix `menu` input to support `null` values.
> Support multiple 1D density estimates.

- packages/core/src/SelectionClause.js
`value` param of `clause*` functions can be nullish (`null | undefined`)
> fix: value param can be nullish in clause functions

- packages/core/src/Coordinator.js
- packages/core/src/MosaicClient.js
- packages/core/src/index.js
- packages/core/src/util/field-info.js
- packages/core/src/util/js-type.js
export two utils functions `queryFieldInfo` and `jsType`
> feat: export queryFieldInfo and jsType

- docs/.vitepress/theme/Layout.vue
- docs/.vitepress/theme/index.js
- docs/index.md
Fixes issue identified in https://github.com/uwdata/mosaic/pull/634#issuecomment-2547939267
Found the solution at https://github.com/ts-safeql/safeql/pull/26/files
I even tried embedding a live example. It works but takes a bit to load so better not to it on the homepage. Instead, I made the video a link to the crossfilter example.
> fix: embed video in video tag

- packages/duckdb-server-rust/Cargo.lock
- packages/duckdb-server-rust/Cargo.toml
- packages/duckdb-server-rust/src/app.rs
- packages/duckdb-server-rust/src/main.rs
- packages/duckdb-server-rust/src/test.rs
This PR adds a few command line arguments for `duckdb-server-rust`.
I used [`clap`](https://docs.rs/clap/latest/clap/) for parsing arguments.
I set the database path as positional argument following the Python server (`duckdb-server`).
I am new to Rust so please review this carefully :)
```
> ./duckdb-server --help                                       
DuckDB Server for Mosaic.
Usage: duckdb-server [OPTIONS] [DATABASE]
Arguments:
[DATABASE]  Path of database file (e.g., "database.db". ":memory:" for in-memory database) [default: :memory:]
Options:
-p, --port <PORT>                                  HTTP Port [default: 3000]
--connection-pool-size <CONNECTION_POOL_SIZE>  Max connection pool size [default: 10]
--cache-size <CACHE_SIZE>                      Max number of cache entries …
```
> feat: add command line args for duckdb-server-rust

- packages/core/src/connectors/rest.js
The Rust server sends error messages to the client if the query fails (e.g., SQL syntax error, incorrect column name).
However, the current `restConnector` does not handle the error message from the server and tries to parse the response just based on the request type.
This PR adds a check whether the response was successful. If the response is not [`ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok), then it throws an error with the response text that contains the error messages from the server.
With this change, `queryError` receives an Error instance with the error message from the server.
The error message format could be improved.
> feat: improve restConnector error handling

- packages/duckdb-server-rust/src/app.rs
- packages/duckdb-server-rust/src/main.rs
Add `--address` as part of CLI arguments. The default is `127.0.0.1` and if parsing the given value fails, it falls back to `Ipv4Addr::LOCALHOST`
```
> ./duckdb-server --help                       
DuckDB Server for Mosaic.
Usage: duckdb-server [OPTIONS] [DATABASE]
Arguments:
[DATABASE]  Path of database file (e.g., "database.db". ":memory:" for in-memory database) [default: :memory:]
Options:
-a, --address <ADDRESS>                            HTTP Address [default: 127.0.0.1]
-p, --port <PORT>                                  HTTP Port [default: 3000]
--connection-pool-size <CONNECTION_POOL_SIZE>  Max connection pool size [default: 10]
--cache-size <CACHE_SIZE>                      Max number of cache entries [default: 1000]
-h, --help                                         Print help …
```
> feat: add address arg for duckdb-server-rust

- packages/plot/src/marks/ConnectedMark.js
- Fix connected marks (`lineY`, `areaX`, etc) by ordering points using the output column name, not the input field. This allows downstream optimizations like preaggregation to work as they should.
Close #676.
> Order connected mark by output name, not input field.

- docs/api/sql/aggregate-functions.md
- packages/core/src/preagg/sufficient-statistics.js
- packages/core/test/preaggregator.test.js
- packages/spec/src/config/transforms.js
- packages/spec/src/spec/Transform.ts
- packages/sql/src/functions/aggregate.js
- packages/sql/src/index.js
- packages/sql/test/aggregate.test.js
- packages/vgplot/src/api.js
This pull request introduces a new aggregate function — `geomean` — to the `mosaic-sql` package for computing the geometric mean.
- Add `geomean` aggregate function
- Add preaggregation handling (in `sufficient-statistics.js`)
- Add tests (in `preaggregator.test.js` and `aggregate.test.js`)
- Update documentation
The JSON schema file has not yet been updated.
It is currently unclear whether this file will be auto-generated or if a manual modification is required.
> Add Aggregate Function `geomean` (mosaic-sql)

- packages/inputs/src/Menu.js
- packages/inputs/src/Search.js
- packages/inputs/src/Slider.js
- packages/inputs/src/Table.js
- packages/inputs/src/input.js
- Add `Input` class, update inputs to inherit from it.
- Add types for input generation methods.
- Add types and docs for table options.
> Refactor inputs, add better types.

- packages/widget/pyproject.toml
- uv.lock
Currently, it is not possible to directly `%pip install mosaic-widget` in a Pyodide environment, since Pyodide distributes `duckdb==1.1.2` while `mosaic-widget` requires `duckdb>=1.1.3`.
This PR would make it easier to work on issues such as #624 which explore Python notebook-based web intergrations of Mosaic.
For example, to create [Marimo based Spec Playground](https://marimo.app/#code/JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoBGLjgJhZpEYMEwTJUHAIIiAFAEoMaAALCwHAMZ4ANttl1g5PJg0QjjACpQArnkVGAZnEyyQEeQC40cHwggcQclkoFlCAYjgAWQgAZ0RgDQ84AAUAT3oIAjgAdTwAIxTtRFScKAhrAnJQlkVfOCg8GGsoAiVVEU0dPQMjEzM8Sxs7NEdnVwgAGjgYsDwNTBBGxHJSRE9vXxm5zHIysHIIKizmNw5rYA5diH3DglkNup9rmGBMmMYAb0WYRABtFgIiEWLAAuklvn8WIZQXAHNAEEs4MAslt5hCVj8AL4TB6PABuiG0tkYqIWSwxfzYIP+gOBIJxj18RTyOkYAHIAMo6ObwABqwBi1 …
> chore: losen `duckdb` dependency for Pyodide compatibility

- README.md
- docs/api/sql/queries.md
- packages/sql/src/ast/query.js
- packages/sql/src/transforms/m4.js
M4 query performance can be improved by a factor of up to 4 using materialized CTEs.
Consider the following benchmark example
```yaml
meta:
title: NOAA Global Historical Climatology Network Daily (GHCN-D)
description: >
Time series showing the daily number of weather stations in use, based
on a dataset of 20 million daily weather observations from 1890 to 2024.
data:
noaa: { file: data/noaa_20m.parquet }
plot:
- mark: lineY
data: { from: noaa }
x: date
y: { count:  }
stroke: steelblue
xLabel: Date
yLabel: Total Stations
width: 800
height: 400
```
Executing the M4 query from above line chart on a MacBook Pro (M1 Pro) produces the following timings
|        | CTE Usage | Duration |
| -----: | :-------: | -------: |
| Before |    no     |  1,355ms |
|  After |    yes    |    362ms |
- Add …
> Improve M4 Query Performance

- docs/api/sql/expressions.md
- docs/api/sql/queries.md
- packages/sql/src/ast/query.js
- packages/sql/src/ast/with.js
- packages/sql/src/functions/cte.js
- packages/sql/src/index.js
- packages/sql/src/transforms/m4.js
- packages/sql/src/types.ts
- packages/sql/test/cte.test.js
- packages/sql/test/query.test.js
- Add `cte(...)` method for direct construction of WITH clause nodes.
- Add `materialized` property to WITH clause nodes to control explicit CTE materialization.
- Update M4 transform to enforce CTE materialization.
Close #693.
> feat: Add cte method for fine-grained WITH clause control.

- packages/spec/src/ast-to-dom.js
Improved the typing of the `options` parameter of `ast-to-dom` to be based on `InstantiateContext` as this is what it is being used for.
> feat: improve `ast-to-dom` typing

- package-lock.json
- packages/core/src/QueryManager.js
- packages/core/src/util/cache.js
- packages/publish/package.json
- packages/publish/src/MosaicPublisher.ts
- packages/publish/src/util/constants.ts
- packages/spec/src/ast-to-dom.js
Added better typing to caches and also the ability to import/export caches to Arrow IPC stream format. Then integrated this new functionality into the `publish` package alongisde better type propogation to ensure everything is working properly.
> **IMPORTANT NOTE:** When this is merged a new release will need to be cut due to the use of the new `.import()` function in the generated code as part of publish. This could be fixed by bundling current version of external packages into published visualization directory and refrencing this instead of CDN but let's discuss this in #682.
> feat: Add cache exporting and hydration capabilities

- examples/svelte-example/src/App.svelte
- examples/vega-example/src/main.js
- examples/vega-example/vite.config.js
also don't need to create a function for top level await anymore
> fix: do not await wasm connector

- packages/core/src/MosaicClient.js
- Fix request update calls to be no-ops when clients are not registered with a coordinator.
> Safeguard calls on unregistered clients.

- packages/core/src/preagg/PreAggregator.js
- Fix preagg optimization to abort if active clause is null.
> Abort preagg optimization if active clause is null.

- packages/core/src/preagg/sufficient-statistics.js
- packages/core/test/preaggregator.test.js
- packages/sql/src/functions/util.js
- packages/sql/src/index.js
- Add `coalesce` SQL function, which returns the first non-null argument.
- Fix preaggregation `count` measures to return zero (not null) for "empty" counts.
> Add coalesce SQL function, use it to fix preaggregation counts

- packages/core/src/Coordinator.js
- packages/core/src/MosaicClient.js
- packages/core/src/make-client.js
- packages/core/test/client.test.js
- Add client `enabled` property. When `enabled` is set to false, the client will not initialize nor respond to query requests and selection updates. This setting can improve performance, for example by suppressing updates to off-screen interface components. When `enabled` is set to true, any pending initialization or query requests will then proceed.
- Add `enabled` option to `makeClient` helper utility.
- Refactor initialization logic between coordinator and client.
- Add tests for client `enabled` property.
> Add client.enabled property.

- packages/core/src/make-client.js
- Add `filterStable` option to makeClient.
> Add filterStable option to makeClient.

- packages/duckdb-server-rust/Cargo.lock
- packages/duckdb-server-rust/Cargo.toml
- packages/duckdb-server/pkg/server.py
- packages/duckdb-server/pyproject.toml
- packages/widget/mosaic_widget/__init__.py
- packages/widget/pyproject.toml
- uv.lock
Removing pinning for dev dependencies since we are using a lockfile anyway.
> chore: update rust and python dependencies

- packages/core/src/Coordinator.js
- packages/core/src/MosaicClient.js
- packages/core/src/QueryManager.js
- packages/core/src/connectors/Connector.ts
- packages/core/src/connectors/rest.js
- packages/core/src/connectors/socket.js
- packages/core/src/connectors/wasm.js
- packages/core/src/index-types.ts
- packages/core/src/make-client.js
- packages/core/src/types.ts
- packages/core/src/util/cache.js
- packages/core/src/util/void-logger.js
- packages/widget/src/index.js
- Add database connector types.
- Add class-based implementations of socket and wasm connectors.
- Add `destroy` method to client, transferred from `make-client` helper.
> Add classes/types for database connectors.

- packages/widget/pyproject.toml
- packages/widget/src/index.js
- uv.lock
fixes #746
New version of https://github.com/uwdata/mosaic/pull/747. Thanks @declann. 
Uses https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze to avoid mutation of params object.
> fix: avoid param mutation

- packages/duckdb-server-rust/Cargo.lock
- packages/duckdb-server-rust/Cargo.toml
Update DuckDB Rust client to `>= 1.2.2`. [The version 1.2.2 includes many bug fixes](https://github.com/duckdb/duckdb/releases/tag/v1.2.2) including https://github.com/duckdb/duckdb/pull/16691
Note that [`version = "1.2.2"` represents the version range `>=1.2.2, <2.0.0`](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#version-requirement-syntax)
> chore: update duckdb rust client

- package.json
- packages/core/package.json
- packages/inputs/package.json
- packages/plot/package.json
- packages/spec/package.json
- packages/sql/package.json
- packages/vgplot/package.json
fixes #796
At least this now includes the files in `dist` in the package. I don't know exactly what runs for a deploy but somehow the tsc build needs to run as well (which it should because it's in `prepublishOnly`).
> fix: explicitly list files for core package

- docs/.vitepress/config.js
- packages/core/package.json
- packages/core/vitest.config.ts
- packages/duckdb/package.json
- packages/duckdb/vitest.config.ts
- packages/inputs/package.json
- packages/inputs/vitest.config.ts
- packages/plot/package.json
- packages/plot/vitest.config.ts
- packages/spec/package.json
- packages/spec/vitest.config.ts
- packages/sql/package.json
- packages/sql/vitest.config.ts
- packages/vgplot/package.json
- packages/vgplot/vitest.config.ts
- packages/widget/package.json
- vite.config.js
Tests and the docs now use aliases to run Vite so they will pick up the source files---no need to compile/run tsc after making changes. This should also make it easy to use watch tasks without having to worry about picking up the latest changes.
I tested running `npx run clean` at the top level and then compiling the individual packages/running tests etc. 
As a note, `tsc` just runs typescript in the current package, `tsc --build` also compiles dependencies (if they need to be updated).
You can run `npx tsc --build` or `npx tsc` (if other dependencies are already compiled) to type check any package.
> chore: improve build and test scripts

- packages/server/duckdb-server-rust/Cargo.lock
- packages/server/duckdb-server-rust/Cargo.toml
`chrono-tz` feature needs to be added to support ` TIMESTAMP WITH TIME ZONE` types 
Error message from the rust server
```
duckdb_server::interfaces: Error: Parser error: Invalid timezone "UTC": only offset based timezones supported without chrono-tz feature
```
> fix: add chrono-tz to support TIMESTAMP WITH TIME ZONE

- packages/mosaic/core/src/Coordinator.ts
- packages/mosaic/core/src/util/field-info.ts
With this change, you don't need to override the return type anymore. It defaults to `Table` unless you explicitly set the type to `json`. This should also make it easy to transition to a future where we remove the json response support.
> feat: query method returns Table when query type is arrow

- packages/mosaic/core/src/SelectionClause.ts
- packages/mosaic/core/test/client.test.ts
- packages/mosaic/core/test/make-client.test.ts
The symptom: clause.source doesn't accept a MosaicClient. If you define a simple client like:
```js
let client = makeClient(...);
selection.update({
source: client,
...
});
```
You'll get a type error on "Type 'MosaicClient' has no properties in common with type 'ClauseSource'". Right now we have to cast the client to `ClauseSource` like `client as ClauseSource`.
I think we can fix it by changing `ClauseSource` to:
```ts
export type ClauseSource = object & { reset?: () => void; };
```
This should match any object, but also objects with a reset method (and if there is a reset method, it must match be of type `() => void`) .
> fix: clause.source doesn't accept a MosaicClient

- packages/vgplot/inputs/src/Menu.js
- packages/vgplot/spec/src/spec/Input.ts
This adds `listMatch` as a new option to the spec, and adds support to the menu.js input
> It might be cleaner to create a separate (or sub-classed) Menu component (ListMenu?) specific to list-type data
@jheer My pitch to not subclass it differently is that the UI/UX is the same, whether using `isIn` to filter by rows, or `list_has_any` to filter by a nested list. The implementation ended up being only ~10 lines. Here's a working implementation from spec to mosaic dev, with the `Keyword Group` dropdown populated from a list, and `Domain` populated normally, and the user couldn't tell the difference in the underlying data model.
To make the experience even more seamless, I think it would be awesome to have column metadata available and automatically handle list columns, with `listMatch` …
> feat: add list support to spec + menu

- packages/vgplot/inputs/src/Table.js
This pull request makes minor corrections to the documentation and comments in the `Table.js` file, primarily fixing typos and improving clarity. No functional code or logic changes are included.
Documentation and comment improvements:
* Fixed multiple instances of the typo "horiztonal" to "horizontal" in parameter descriptions for the `align` option. [[1]](diffhunk://#diff-18df6624afdc7db3ca2a6eb17ec293ed23c6d0ce926e01ef91c6cdf06e5962f1L22-R22) [[2]](diffhunk://#diff-18df6624afdc7db3ca2a6eb17ec293ed23c6d0ce926e01ef91c6cdf06e5962f1L60-R60)
* Corrected "widts" to "widths" in parameter descriptions for the `width` option. [[1]](diffhunk://#diff-18df6624afdc7db3ca2a6eb17ec293ed23c6d0ce926e01ef91c6cdf06e5962f1L35-R35) [[2]](diffhunk://#diff-18df6624afdc7db3ca2a6eb17ec293ed23c6d0ce926e01ef91c6c …
> docs: fix typo and remove unused import

- packages/mosaic/sql/src/index.ts
- packages/mosaic/sql/src/visit/codegen/duckdb.ts
- packages/mosaic/sql/src/visit/codegen/sql.ts
- packages/mosaic/sql/test/query.test.ts
- packages/vgplot/plot/src/transforms/bin.js
- Update `CUSTOM` node handling to pass through SQL codegen visitor.
- Update vgplot `bin` transform to use pass-through visitor.
- Use `DESC` rather than `DESCRIBE` for broader compatibility.
- Fix SQL codegen to ensure application of current visitor, not default node `toString()`.
> Fixes to SQL code gen.

- packages/mosaic/sql/src/transforms/bin-histogram.ts
- packages/mosaic/sql/src/transforms/util/time-interval.ts
- packages/mosaic/sql/test/bin.test.ts
- Fix `binDate` and `binHistogram` helpers to handle degenerate (min == max) spans.
> Handle degenerate bin spans.

- docs/public/specs/esm/region-tests.js
- docs/public/specs/json/region-tests.json
- docs/public/specs/yaml/region-tests.yaml
- packages/vgplot/plot/src/marks/util/guide-marks.js
- packages/vgplot/plot/src/plot-renderer.js
- packages/vgplot/plot/src/plot.js
- specs/esm/region-tests.js
- specs/json/region-tests.json
- specs/ts/region-tests.ts
- specs/yaml/region-tests.yaml
- Overhaul mark-to-svg indexing.
Interactors (such as `region`) look up the SVG for a mark based on a provided index. This PR updates this indexing scheme to always skip "guide" marks such as axes, grids, and frames. This avoids potential interactions with automatically added (as opposed to explicitly specified) guides, removing errors that can cause interactors to fail.
Close #897.
> Overhaul mark-to-svg indexing.
